
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: "Install"
  inputs:
    command: 'install'
- task: Npm@1
  displayName: "Test"
  inputs:
    command: 'custom'
    customCommand: 'run test-ci'
- task: Npm@1
  displayName: "Build"
  inputs:
    command: 'custom'
    customCommand: 'run build --prod'

